config/routes.rb
Rails.application.routes.draw do
  root 'user#landing'
  
  if Rails.env == "development"
    mount SamlCamel::Engine, at: "/saml"
  end


  scope :user do
    get '/progress/:id' => 'user#project_status', as: 'project_status'
    get '/show_sp' => 'user#show_sp', as: "show_user_sp", :constraints => { :entityId => /[0-z\D]+/ }
    post '/create_user_note' => 'user#create_user_note'
    post '/sp/check_cert' => 'registration#check_cert' #check cert from user path
  end


  scope :register do
    get '/register' => 'registration#new'
    get '/sp' => 'registration#new_sp', as: 'new_sp'

  	post 'register/create_registration' => 'registration#create'
    post '/sp/check_cert' => 'registration#check_cert' #check csp cert
  	post '/edit_sp' => 'registration#edit_sp', as: 'edit_sp'
  	post '/sp/submit' => "registration#submit_new_sp", as: 'submit_sp'

  	delete '/delete_sp' => 'registration#delete_sp', as: 'delete_sp', :constraints => { :entityId => /[0-z\D]+/ }
  end


  scope :admin do
  	get '/' => 'admin#index', as: 'admin_root'
  	get '/open/(:org)' => 'admin#index', as: 'admin_open_request'
  	get '/closed/(:org)' => 'admin#closed', as: 'admin_closed_request'
  	get '/on_hold/(:org)' => 'admin#on_hold', as: 'admin_hold_request'
    get '/details/:id' => 'admin#show', as: 'integration_request'
    get '/statistics' => 'admin#statistics'

  	post '/search/projects' => 'admin#search_projects', as: 'search_projects'
  	post '/set_filter' => 'admin#set_active_filter', as: 'set_active_filter'
  	post '/create_note' => 'admin#create_note'
  	post '/assign_analyst/:id' => 'admin#assign_analyst', as: 'assign_analyst'

  	patch '/update_status/:id' => 'admin#update_status', as: 'component_status'
  	patch '/assign_institution/:id' => 'admin#assign_institution', as: 'assign_institution'
  	patch '/update_note/:id' => 'admin#update_note'

  	delete '/delete_note' => 'admin#delete_note', as: 'work_note'
  end


	scope :spreg do
		get '/' => 'admin/spreg#index', as: 'spreg'
    get '/spreg/search/user' => 'admin/spreg#index', as: "spreg_index"
		get 'show' => "admin/spreg#show", as: "show_sp", :constraints => { :entityId => /[0-z\D]+/ } #allows urls as param
		get 'sps' => "admin/spreg#sp_list"
		post "search" => "admin/spreg#search", as: "search_sp"
    post "search/user" => "admin/spreg#search_by_user", as: "search_by_user"
    post 'attribute_approval' => 'admin/spreg#attribute_approval', as: 'attribute_approval'

    #validate sp cert
    post '/show/sp/check_cert' => 'registration#check_cert'
  	post '/sp/check_cert' => 'registration#check_cert'

		put 'update/:entityId' => "admin/spreg#update", as: "update_sp", :constraints => { :entityId => /[0-z\D]+/ } #allows urls as param
	end


  #other
  get "/docs" => 'documentation#index', as: "docs"
  get "/docs/boxdoc" => 'documentation#box_doc', as: "box_docs"
  get "/logout" => 'application#logout', as: "logout"
  post '/mock_id' => 'application#select_mock_id', as: "mock_id"
  post '/stop_mock' => 'application#stop_mock', as: "stop_mock"
  post '/api' => 'admin/api#create'
  post '/authtest' => 'admin/api#authtest'
  # get '/faq' => 'documentation#faq'
end

app/views/admin/_assign_analyst.html.erb
<%= form_tag(assign_analyst_path(params[:id])) do %>
    <%= select_tag :analyst_assign , options_for_select(@admins) %>
  <%= submit_tag "Assign Analyst", class: "create-btn" %>
<% end %>

app/views/admin/_component_status.html.erb
  <%= form_for(project,url: component_status_path(project.id),:class=>"ss-stylish-form") do |f| %>
      This project is <span style="font-weight: bold;" class="<%= com_color_status(project.status) %>"><%= project.status %></span>.
      <%= select_tag :status, options_for_select(["In Progress","Closed/Complete","Closed/Incomplete","Integration Requested","On Hold","Archive"]) %>
      <%= f.submit "Update Status", class: "create-btn" %>
  <% end %>

app/views/admin/_filter_options.html.erb
<div class="btn-option">
  <%= form_tag(set_active_filter_path) do %>
    <%= hidden_field_tag :org, "university" %>
    <%= submit_tag "Filter University", class: 'active' %>
  <% end %>
</div>

<div class="btn-option">
  <%= form_tag(set_active_filter_path) do %>
    <%= hidden_field_tag :org, "health" %>
    <%= submit_tag "Filter Health", class: 'active' %>
  <% end %>
</div>

<div class="btn-option">

  <%= form_tag(set_active_filter_path) do %>
    <%= hidden_field_tag :org, "" %>
    <%= submit_tag "No Filter", class: 'active' %>
  <% end %>
</div>

app/views/admin/_note_form.html.erb
<%= form_for(@work_note,:url => {:action => "create_note",:class => 'ss-stylish-form'}) do |note| %>

      <div class="am-form-pair">
        <%= note.label "Notes" %>
        <p>Make Public?<%= note.check_box :is_public, :id => "confirm-public" %></p>
        <%= note.text_area :note ,:size => "100x10"%>
        <%= note.hidden_field :project_id, :value => params[:id] %>
      </div>


  <div>
    <%# submit_tag 'Add Work Note',:class => "active"%>
    <button type="submit" class="active">Add Work Note<i class="button-icon-right fa fa-plus"></i></button>
  </div>
<% end %>

app/views/admin/_project_assignment.html.erb
<table id="admin-assign-table">
  <tbody>


  <tr>
    <%= form_tag(assign_analyst_path(params[:id])) do %>
        <td>Assigned To: <%= @project.analyst %></td>
        <td><%= select_tag :analyst_assign , options_for_select(@admins) %></td>
        <td><%= submit_tag "Assign Analyst", class: "active" %></td>
    <% end %>
  </tr>
  <tr>
    <%= form_for(@project ,:url => {:action => "assign_institution",:id => @project.id}) do |project| %>
      <td>Project Handled by: <%= @project.institution %></td>
      <td><%= project.select :institution, options_for_select([ "University", "Health System" ], "MasterCard") %></td>
      <td><%= submit_tag 'Assign Handler', class: 'active' %></td>
    <% end %>
  </tr>

  <tr>
    <%= form_for(@project,url: component_status_path(@project.id),:class=>"ss-stylish-form") do |f| %>
        <td>This project is <span style="font-weight: bold;" class="<%= com_color_status(@project.status) %>"><%= @project.status %></span>.</td>
        <td><%= select_tag :status, options_for_select(["In Progress","Closed/Complete","Closed/Incomplete","Integration Requested","On Hold","Archive"]) %></td>
        <td><%= f.submit "Update Status", class: "active" %></td>
    <% end %>
  </tr>


  </tbody>
</table>

app/views/admin/_work_notes.html.erb
<table class="display full-width">
  <tbody>
    <% @work_notes.each do |i| %>
      <% i.updated_by ? worker=i.updated_by : worker="Anonymous" %>
      <tr>
        <td>
          <div class="wn">
            <div class="wn-bar">
              <p class="wn-worker"><%= worker %> - <%= i.created_at.strftime("%B %d,%Y | %l:%M%P") %>
                <span class="sp-icon wn-edit-icon"><i class="fa fa-edit wn-edit-icon" aria-hidden="true"></i></span>
                <%= form_tag(work_note_path(id: i.id), method: :delete, id: 'del-wn-form') do %>
                  <button id="delete-sp-btn"  type="submit" onclick="return confirm('Are you sure you want to delete this Work Note?')">
                    <i class='fa fa-trash' aria-hidden='true'></i>
                  </button>
                <% end %>
              </p>
            </div>

            <%= simple_format(i.note,class: "wn-note") %>

            <div class="wn-update-form">
              <%= form_for(i,:url => {:action => "update_note",:id => i.id}) do |f| %>
                <%= f.text_area :note , class: "wn-update", size: "150X50"%>
                <div class="clearfix"></div>
                <%= f.submit "Update Work Note", class: "active"%>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/index.html.erb
<div id="main-no-aside">
 <h2 id="admin-root-header">Shibboleth Integration Requests (<%=@projects.count %>)</h2>

  <div>
    <h4>Last Updated Key</h4>
    <p><span class="key-green">&#9679; 1wk</span>  <span class="key-blue">&#9679; 2wk</span>  <span class="key-orange">&#9679; 3wk</span>  <span class="key-red">&#9679; 4wk</span></p>
  </div>


  <%= render partial: "filter_options" %>

  <div class="clearfix"></div>

  <div>
    <%= form_tag(search_projects_path) do %>
      <%= label_tag "Search Integrations" %>
      <%= text_field_tag :search %>
      <%= submit_tag "Search Integrations", class: 'active'%>
    <% end %>
  </div>

  <!--<table class="idms-data-table">-->
  <table id="integration-table" class=" display tablesorter full-width">
    <thead>
      <tr>
        <th>PROJECT NAME</th>
        <th>SPONSOR</th>
        <th>STATUS</th>
        <th>REQUESTED ON</th>
        <th>LAST UPDATED</th>
        <th>HANDLER</th>
        <th>ANALYST</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr class="click-row" data-link="<%= integration_request_path(project.id)%>">
          <td><%= project.name %></td>
          <td><%= project.sponsor %> (<%= project.sponsor_duid %>)</td>
          <td><%= project.status %></td>
          <td><%= project.created_at.strftime("%B %d, %Y") %></td>
          <% work_notes = project.work_notes %>
          <% if work_notes[0] %>
            <td class="<%= color_status(project.updated_at.strftime("%B %d, %Y"),closed) %>"> <%= project.updated_at.strftime("%B %d, %Y")%></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= project.institution %></td>
          <td><%= project.analyst %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/show.html.erb
<div id="main-no-aside">
  <!--Work note flash-->
  <% if flash[:success] %>
    <div class=" message success">
      <%= flash[:success].html_safe %>
    </div>
  <% elsif flash[:error]%>
    <div class="message error">
      <%= flash[:error].html_safe %>
    </div>
  <% end %>


  <% project = @project %>
  <div class="content-section">
    <h1><%= project.name %></h1>
    <h3>Sponsor: <%= project.sponsor %>, <%= project.sponsor_duid %>, <%= project.sponsor_email %> <button id="show-work-note" class="active">Work Notes</button></h3>
    <% if project.ticket  %>
      <h3>Service Now Ticket: <%= project.ticket %></h3>
    <% end %>
    <%= render :partial => 'project_assignment' %>
  </div>
  <div class="clearfix"></div>

  <div class="content-section">
    <h4>Request for help details:</h4>
    <%= simple_format(project.help_details) %>

    <% if project.is_web_based %>
      <ul>
        <li><span class="bold-title">Web Based:</span> <%= project.is_web_based %></li>
        <li><span class="bold-title">Production Url:</span> <%= project.prod_url %></li>
        <li><span class="bold-title">Test Url:</span> <%= project.test_url %></li>
        <li><span class="bold-title">Webserver:</span> <%= project.webserver %></li>
        <li><span class="bold-title">OS:</span> <%= project.os %></li>
        <li><span class="bold-title">Requested On:</span> <%= project.created_at.strftime("%B %d,%Y at %I:%M %P (%Z)") %></li>
        <li><span class="bold-title">Supports Saml:</span> <%= project.is_saml_supported %></li>
        <li><span class="bold-title">Vendor App:</span> <%= project.is_vendor %></li>
      </ul>
    <% else %>
      <div>Non Web Description: <%= project.non_web_desc %></div>
    <% end %>
  </div>


  <div class="content-section">
    <% contacts = project.contacts %>
    <h4>Contacts:</h4>
    <% contacts.each do |i| %>
      <ul>
        <li><span class="bold-title">Name:</span> <%= i.name %></li>
        <li><span class="bold-title">Contact Type:</span> <%= i.contact_type %></li>
        <li><span class="bold-title">Netid:</span> <%= i.netid %></li>
        <li><span class="bold-title">Email:</span> <%= i.email %></li>
        <li><span class="bold-title">Employer:</span> <%= i.employer %></li>
      </ul>
    <% end %>
  </div>


  <div id="work-note-container">
    <h4>Work Notes:</h4>
    <%= render :partial => "work_notes" %>
    <%= render :partial => "note_form" %>
  </div>
</div>