config/routes.rb
Rails.application.routes.draw do
  root 'user#landing'
  
  if Rails.env == "development"
    mount SamlCamel::Engine, at: "/saml"
  end


  scope :user do
    get '/progress/:id' => 'user#project_status', as: 'project_status'
    get '/show_sp' => 'user#show_sp', as: "show_user_sp", :constraints => { :entityId => /[0-z\D]+/ }
    post '/create_user_note' => 'user#create_user_note'
    post '/sp/check_cert' => 'registration#check_cert' #check cert from user path
  end


  scope :register do
    get '/register' => 'registration#new'
    get '/sp' => 'registration#new_sp', as: 'new_sp'

  	post 'register/create_registration' => 'registration#create'
    post '/sp/check_cert' => 'registration#check_cert' #check csp cert
  	post '/edit_sp' => 'registration#edit_sp', as: 'edit_sp'
  	post '/sp/submit' => "registration#submit_new_sp", as: 'submit_sp'

  	delete '/delete_sp' => 'registration#delete_sp', as: 'delete_sp', :constraints => { :entityId => /[0-z\D]+/ }
  end


  scope :admin do
  	get '/' => 'admin#index', as: 'admin_root'
  	get '/open/(:org)' => 'admin#index', as: 'admin_open_request'
  	get '/closed/(:org)' => 'admin#closed', as: 'admin_closed_request'
  	get '/on_hold/(:org)' => 'admin#on_hold', as: 'admin_hold_request'
    get '/details/:id' => 'admin#show', as: 'integration_request'
    get '/statistics' => 'admin#statistics'

  	post '/search/projects' => 'admin#search_projects', as: 'search_projects'
  	post '/set_filter' => 'admin#set_active_filter', as: 'set_active_filter'
  	post '/create_note' => 'admin#create_note'
  	post '/assign_analyst/:id' => 'admin#assign_analyst', as: 'assign_analyst'

  	patch '/update_status/:id' => 'admin#update_status', as: 'component_status'
  	patch '/assign_institution/:id' => 'admin#assign_institution', as: 'assign_institution'
  	patch '/update_note/:id' => 'admin#update_note'

  	delete '/delete_note' => 'admin#delete_note', as: 'work_note'
  end


	scope :spreg do
		get '/' => 'admin/spreg#index', as: 'spreg'
    get '/spreg/search/user' => 'admin/spreg#index', as: "spreg_index"
		get 'show' => "admin/spreg#show", as: "show_sp", :constraints => { :entityId => /[0-z\D]+/ } #allows urls as param
		get 'sps' => "admin/spreg#sp_list"
		post "search" => "admin/spreg#search", as: "search_sp"
    post "search/user" => "admin/spreg#search_by_user", as: "search_by_user"
    post 'attribute_approval' => 'admin/spreg#attribute_approval', as: 'attribute_approval'

    #validate sp cert
    post '/show/sp/check_cert' => 'registration#check_cert'
  	post '/sp/check_cert' => 'registration#check_cert'

		put 'update/:entityId' => "admin/spreg#update", as: "update_sp", :constraints => { :entityId => /[0-z\D]+/ } #allows urls as param
	end


  #other
  get "/docs" => 'documentation#index', as: "docs"
  get "/docs/boxdoc" => 'documentation#box_doc', as: "box_docs"
  get "/logout" => 'application#logout', as: "logout"
  post '/mock_id' => 'application#select_mock_id', as: "mock_id"
  post '/stop_mock' => 'application#stop_mock', as: "stop_mock"
  post '/api' => 'admin/api#create'
  post '/authtest' => 'admin/api#authtest'
  # get '/faq' => 'documentation#faq'
end

app/models/spreg/user.rb
class Spreg::User < Spreg::Base
	has_and_belongs_to_many :sps


	def get_entity_ids
		begin
			ids = []
			sps = self.sps
			sps.each do |sp|
				reg = {}

				reg[:entity_id] = sp.entity_id
				reg[:name] = sp.public_name
				reg[:last_update] = sp.updated_at


				ids << reg
			end
			ids
		rescue
			false
		end
	end


end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def landing
		@eppn = @shib_attrs[:eppn]
		# @saved_sps = SpInProgress::SavedSp.where eppn: @eppn
		@projects = Project.where(sponsor_email: @shib_attrs[:eppn])
		@has_projects = @projects.count != 0 && @projects.count

		netid = @shib_attrs[:uid]
		sp_user = Spreg::User.find_by(netid: netid)
		@sp_user = sp_user
		sp_user ? @sps = sp_user.get_entity_ids : @sp_user = false
	end


	def project_status
		@project = Project.find_by id: params[:id]
		@work_note = WorkNote.new
		@work_notes = @project.work_notes.where(is_public: true)
	end


	#post
	def create_user_note
		@work_note = WorkNote.new(work_note_params(params))
		@work_note.updated_by = @shib_attrs.dig(:display_name)
		@work_note.is_public = true

		if @work_note.save
			flash[:success] = "Work Note Added."
			redirect_back(fallback_location: root_path)
		else
			flash[:error] = "Please enter a work note."
			redirect_back(fallback_location: root_path)
		end
	end


	#get
	def show_sp
		@is_admin = is_admin
		@attributes = Spreg::Attribute.where(available: 1).pluck(:attributeID,:is_public) #attributes to populate drop down
		@sp = SpRegistration.new(params[:entityId].strip)
		authorize_sp_user(@sp)
		@pending ||= Spreg::PendingSp.find_by new_entity_id: params[:entityId]
		@pending ||= Spreg::PendingSp.find_by new_entity_id: "http://#{params[:entityId]}"
		@pending ||= Spreg::PendingSp.find_by new_entity_id: "https://#{params[:entityId]}"


		render "admin/spreg/show"
	end




	private
	def work_note_params(my_params)
		my_params.require(:work_note).permit(:note,:project_id)
	end

end

app/helpers/user_helper.rb
module UserHelper
	def drop_http(entity_id)
		entity_id.gsub("https://","").gsub("http://","")
	end
end

app/views/user/_note_form.html.erb
<%= form_for(@work_note,:url => {:action => "create_user_note",:class => 'ss-stylish-form'}) do |note| %>
    <div class="am-form-pair">
      <%= note.text_area :note ,:size => "100x10"%>
      <%= note.hidden_field :project_id, :value => params[:id] %>
    </div>


    <div>
      <%= submit_tag 'Add Work Note',:class => "active"%>
    </div>
<% end %>

app/views/user/_sps.html.erb
<h2>Your Shibboleth Service Providers </h2>
<!--<table id="user-sp-table" class="idms-data-table tablesorter">-->
<table id="user-sp-table" class="display full-width tablesorter">
  <thead>
  <tr>
    <th>Entity ID</th>
    <th>Last Updated</th>
  </tr>
  </thead>

  <tbody>
  <% @sps.each do |sp| %>

    <tr class="click-row" data-link="<%= show_user_sp_path(entityId: drop_http(sp[:entity_id]))%>">
      <td><%= sp[:entity_id] %></td>
      <td><%= sp[:last_update].strftime("%B %d, %Y") if sp[:last_update] %></td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/user/_user_menu.html.erb
<h1 id="root-header">Authenticating Your Duke Site</h1>
<div class="content-section">
<p>Duke supports electronic authorization to resources via <a href="https://shibboleth.net/">Shibboleth</a>, an open-source authorization provider created by <a href="http://www.internet2.edu/">Internet2</a>, a community of academic, research, industrial, and governmental institutions.</p>
  <%= form_tag(docs_path, method: "GET") do %>
    <h2><button type='submit' class="active">Read Documentation<i class="button-icon-right fa fa-arrow-right"></i></button></h2>
  <% end %>
  <p>
    Great place to start whether you are new to Shibboleth or just looking for documentation on Shibboleth
    installation and configuration.
  </p>


  <%= form_tag(new_sp_path, method: "GET") do %>
    <h2><button class="active">Register with the Duke Identity Provider<i class="button-icon-right fa fa-arrow-right"></i></button></h2>
  <% end %>
  <p>Already have a working Service Provider? Register with the Duke Identity Provider here!</p>


  <%= form_tag(register_path, method: "GET") do %>
    <h2><button class="active">Stuck on a SP Integration?<i class="button-icon-right fa fa-arrow-right"></i></button></h2>
  <% end %>
  <p>
    If you have started the Shibboleth integration process and are having trouble installing or configuring your
    Shibboleth Service Provider, you can request assistance from OIT here.
  </p>
</div>

app/views/user/_user_projects.html.erb
<h2>Your Open Shibboleth Integrations</h2>

<table id="user-projects-table" class="display full-width tablesorter">
  <thead>
  <tr>
    <th>Project</th>
    <th>Status</th>
    <th>IDM Contact</th>
    <th>Last Updated</th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |p| %>
      <tr class="click-row" data-link="<%= project_status_path(p.id)%>">
        <td><%= p.name %></td>
        <td><%= p.status %></td>
        <td><%= p.analyst %></td>
        <% if p.work_notes[0] %>
            <td> <%= p.updated_at.strftime("%B %d, %Y")%></td>
        <% else %>
            <td></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/user/_work_notes.html.erb
<table class="idms-data-table">
  <tbody>
  <% @work_notes.each do |i| %>
      <% i.updated_by ? worker=i.updated_by : worker="Anonymous" %>
      <tr>
        <td>
          <div class="wn">
            <!-- removed time h:mm because was not showing in prod or acceptance-->
            <p class="wn-worker"><%= worker %> - <%= i.created_at.strftime("%B %d,%Y") %></p>
            <p class="wn-note"><%= i.note %></p>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/user/landing.html.erb
<div id="main-no-aside">
  <% if flash[:success] %>
    <div class="notice">
      <%= flash[:success].html_safe %>
    </div>
  <% elsif flash[:error]%>
    <div class="notice-error">
      <%= flash[:error].html_safe %>
    </div>
  <% end %>

  <%= render :partial => "user_menu" %>

  <%# unless @saved_sps.empty? %>
    <%# render :partial => "saved_sps", locals: {saved_sps: @saved_sps} %>
  <%# end %>

  <% if @sps %>
    <%= render :partial => "sps" %>
  <% end %>

  <% if @has_projects %>
    <%= render :partial => "user_projects" %>
  <% end %>
</div>

app/views/user/project_status.html.erb
<div id="main-no-aside">
  <h2>Project Status</h2>

  <div class="docs-container">
    <h4>Project Sponsor:</h4>
    <p><%= @project.sponsor %>, <%= @project.sponsor_duid %>, <%= @project.sponsor_email %> </p>
  </div>
  <div class="docs-container">
    <h4>Current Status:</h4>
    <p><%= @project.status %></p>
  </div>

  <h2>Work Notes</h2>

  <%= render :partial => "work_notes" %>
  <%= render :partial => "note_form" %>
</div>