config/routes.rb
Rails.application.routes.draw do
  root 'user#landing'
  
  if Rails.env == "development"
    mount SamlCamel::Engine, at: "/saml"
  end


  scope :user do
    get '/progress/:id' => 'user#project_status', as: 'project_status'
    get '/show_sp' => 'user#show_sp', as: "show_user_sp", :constraints => { :entityId => /[0-z\D]+/ }
    post '/create_user_note' => 'user#create_user_note'
    post '/sp/check_cert' => 'registration#check_cert' #check cert from user path
  end


  scope :register do
    get '/register' => 'registration#new'
    get '/sp' => 'registration#new_sp', as: 'new_sp'

  	post 'register/create_registration' => 'registration#create'
    post '/sp/check_cert' => 'registration#check_cert' #check csp cert
  	post '/edit_sp' => 'registration#edit_sp', as: 'edit_sp'
  	post '/sp/submit' => "registration#submit_new_sp", as: 'submit_sp'

  	delete '/delete_sp' => 'registration#delete_sp', as: 'delete_sp', :constraints => { :entityId => /[0-z\D]+/ }
  end


  scope :admin do
  	get '/' => 'admin#index', as: 'admin_root'
  	get '/open/(:org)' => 'admin#index', as: 'admin_open_request'
  	get '/closed/(:org)' => 'admin#closed', as: 'admin_closed_request'
  	get '/on_hold/(:org)' => 'admin#on_hold', as: 'admin_hold_request'
    get '/details/:id' => 'admin#show', as: 'integration_request'
    get '/statistics' => 'admin#statistics'

  	post '/search/projects' => 'admin#search_projects', as: 'search_projects'
  	post '/set_filter' => 'admin#set_active_filter', as: 'set_active_filter'
  	post '/create_note' => 'admin#create_note'
  	post '/assign_analyst/:id' => 'admin#assign_analyst', as: 'assign_analyst'

  	patch '/update_status/:id' => 'admin#update_status', as: 'component_status'
  	patch '/assign_institution/:id' => 'admin#assign_institution', as: 'assign_institution'
  	patch '/update_note/:id' => 'admin#update_note'

  	delete '/delete_note' => 'admin#delete_note', as: 'work_note'
  end


	scope :spreg do
		get '/' => 'admin/spreg#index', as: 'spreg'
    get '/spreg/search/user' => 'admin/spreg#index', as: "spreg_index"
		get 'show' => "admin/spreg#show", as: "show_sp", :constraints => { :entityId => /[0-z\D]+/ } #allows urls as param
		get 'sps' => "admin/spreg#sp_list"
		post "search" => "admin/spreg#search", as: "search_sp"
    post "search/user" => "admin/spreg#search_by_user", as: "search_by_user"
    post 'attribute_approval' => 'admin/spreg#attribute_approval', as: 'attribute_approval'

    #validate sp cert
    post '/show/sp/check_cert' => 'registration#check_cert'
  	post '/sp/check_cert' => 'registration#check_cert'

		put 'update/:entityId' => "admin/spreg#update", as: "update_sp", :constraints => { :entityId => /[0-z\D]+/ } #allows urls as param
	end


  #other
  get "/docs" => 'documentation#index', as: "docs"
  get "/docs/boxdoc" => 'documentation#box_doc', as: "box_docs"
  get "/logout" => 'application#logout', as: "logout"
  post '/mock_id' => 'application#select_mock_id', as: "mock_id"
  post '/stop_mock' => 'application#stop_mock', as: "stop_mock"
  post '/api' => 'admin/api#create'
  post '/authtest' => 'admin/api#authtest'
  # get '/faq' => 'documentation#faq'
end

app/models/spreg/attribute.rb
class Spreg::Attribute < Spreg::Base
	has_and_belongs_to_many :saved_sps
end

app/models/spreg/base.rb
class Spreg::Base < ApplicationRecord
	if Rails.application.secrets.legacy_db
		if Rails.env == "production"
			establish_connection :sql_production
		else
			establish_connection :sql_development
		end
	end

	self.abstract_class = true

	def self.gendata
		xml_string = <<-XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<AttributeFilterPolicyGroup xmlns="urn:mace:shibboleth:2.0:afp" xmlns:basic="urn:mace:shibboleth:2.0:afp:mf:basic" xmlns:saml="urn:mace:shibboleth:2.0:afp:mf:saml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="ShibbolethFilterPolicy" xsi:schemaLocation="urn:mace:shibboleth:2.0:afp classpath:/schema/shibboleth-2.0-afp.xsd                         urn:mace:shibboleth:2.0:afp:mf:basic classpath:/schema/shibboleth-2.0-afp-mf-basic.xsd                         urn:mace:shibboleth:2.0:afp:mf:saml classpath:/schema/shibboleth-2.0-afp-mf-saml.xsd">

</AttributeFilterPolicyGroup>
		XML
		File.write('vendor/shibboleth/conf/attribute-filter.xml', xml_string)
	end

	def self.adddata
		doc = File.open("vendor/shibboleth/conf/attribute-filter.xml") { |f| Nokogiri::XML(f) }
		ed = doc.search("AttributeFilterPolicyGroup").first
		new_xml = <<-XML
	<AttributeFilterPolicy id="https://idms-web-netid-test-01.oit.duke.edu/shibboleth">
    <PolicyRequirementRule value="https://idms-web-netid-test-01.oit.duke.edu/shibboleth" xsi:type="basic:AttributeRequesterString"/>
    <AttributeRule attributeID="uid">
      <PermitValueRule xsi:type="basic:ANY"/>
    </AttributeRule>
	  <AttributeRule attributeID="mail">
      <PermitValueRule xsi:type="basic:ANY"/>
    </AttributeRule>
	  <AttributeRule attributeID="sn">
      <PermitValueRule xsi:type="basic:ANY"/>
    </AttributeRule>
	  <AttributeRule attributeID="eduPersonPrimaryAffiliation">
      <PermitValueRule xsi:type="basic:ANY"/>
    </AttributeRule>
	  <AttributeRule attributeID="isMemberOf">
      <PermitValueRule xsi:type="basic:OR">
      <basic:Rule value="urn:mace:duke.edu:groups:oit:csi:is:idmtech" xsi:type="basic:AttributeValueString"/>
      <basic:Rule regex="urn:mace:duke.edu:groups:oit:idm:applications:affiliates:.*" xsi:type="basic:AttributeValueRegex"/>
      <basic:Rule regex="urn:mace:duke.edu:groups:oit:idm:applications:onelink:.*" xsi:type="basic:AttributeValueRegex"/>
      <basic:Rule value="urn:mace:duke.edu:groups:dhts:dhead:dukemedicalmembers" xsi:type="basic:AttributeValueString"/>
      <basic:Rule regex="urn:mace:duke.edu:groups:oit:idm:applications:identity-manager:.*" xsi:type="basic:AttributeValueRegex"/>
      </PermitValueRule>
    </AttributeRule>
		<AttributeRule attributeID="givenName">
	    <PermitValueRule xsi:type="basic:ANY"/>
	  </AttributeRule>
	</AttributeFilterPolicy>
		XML
		ed.add_child(new_xml)
		File.write('vendor/shibboleth/conf/attribute-filter.xml', doc.to_xml)
	end

end

app/models/spreg/owner.rb
class Spreg::Owner < Spreg::Base

  has_and_belongs_to_many :sps, :class_name => 'Spreg::Sp'

  def get_entity_ids
    begin
      ids = []
      sps = self.sps
      sps.each do |sp|
        reg = {}
        reg[:entity_id] = sp.entity_id
        reg[:name] = sp.public_name
        reg[:last_update] = sp.updated_at
      end
    rescue
      false
    end
  end
end

app/models/spreg/pending_sp.rb
class Spreg::PendingSp < Spreg::Base
  belongs_to :sp
  belongs_to :spreg_sp, :class_name => 'Spreg::Sp', foreign_key: :sp_id
end

app/models/spreg/pending_sp_assertion.rb
class Spreg::PendingSpAssertion < Spreg::Base
  belongs_to :sp
  belongs_to :spreg_sp, :class_name => 'Spreg::Sp', foreign_key: :sp_id
end

app/models/spreg/pending_sp_attr.rb
class Spreg::PendingSpAttr < Spreg::Base
  belongs_to :sp
  belongs_to :spreg_sp, :class_name => 'Spreg::Sp', foreign_key: :sp_id
end

app/models/spreg/sp.rb
class Spreg::Sp < Spreg::Base
	has_many :sp_contacts
  has_many :pending_sps, :class_name => 'Spreg::PendingSp'
  has_many :pending_sp_assertions, :class_name => 'Spreg::PendingSpAssertion'
  has_many :pending_sp_attrs, :class_name => 'Spreg::PendingSpAttr'
	has_and_belongs_to_many :users
  has_and_belongs_to_many :owners, :class_name => 'Spreg::Owner'
	#accepts_nested_attributes_for :sp_contacts
end

app/models/spreg/sp_contact.rb
class Spreg::SpContact < Spreg::Base
	belongs_to :sp, foreign_key: :sp_id
end

app/models/spreg/user.rb
class Spreg::User < Spreg::Base
	has_and_belongs_to_many :sps


	def get_entity_ids
		begin
			ids = []
			sps = self.sps
			sps.each do |sp|
				reg = {}

				reg[:entity_id] = sp.entity_id
				reg[:name] = sp.public_name
				reg[:last_update] = sp.updated_at


				ids << reg
			end
			ids
		rescue
			false
		end
	end


end

app/controllers/admin/spreg_controller.rb
class Admin::SpregController < ApplicationController
	layout 'admin'
	include SpregHelper
	before_action :authorize_admin, only: ["index","search","sp_list","attribute_approval"]
	# before_action :authorize_sp_user, only: ["show","update"]


	#get
	def index
		@pending_sp_attrs = Spreg::PendingSpAttr.where(is_approved: false)
	end


	#get
	def show
		entity_id = params[:entityId].strip
		@sp = SpRegistration.new(entity_id)
		authorize_sp_user(@sp)
		@is_admin = is_admin
		if @sp.sp
			@attributes = Spreg::Attribute.where(available: 1).pluck(:attributeID,:is_public) #attributes to populate drop down
			@pending = Spreg::PendingSp.find_by new_entity_id: @sp.entity_id
		else
			redirect_to action: 'index'
		end
	end


	def search_by_user
		user = Spreg::User.find_by(netid: params[:netid])
		if user
			@pending_sp_attrs = Spreg::PendingSpAttr.where(is_approved: false)
			@potential_matches = user.sps.pluck(:entity_id)
			render "index"
		else
			@pending_sp_attrs = Spreg::PendingSpAttr.where(is_approved: false)
			flash[:error] = "Unable to any SPs registered to #{params[:netid]}"
			redirect_to action: 'index'
		end
	end

	#post
	def search
		potential_matches = []
		sps = JSON.parse(SpRegistration.sps(typeahead: false))
		sps.each{ |sp| potential_matches << sp if sp.match(params[:entityId]) }

		if potential_matches.size > 1
			@pending_sp_attrs = Spreg::PendingSpAttr.where(is_approved: false)
			@potential_matches = potential_matches
			render "index"
		elsif potential_matches.size == 1
			redirect_to show_sp_path(entityId: potential_matches.join(""))
		else
			flash[:error] = "Unable to find entity ID #{params[:entityId]}"
			redirect_to action: 'index'
		end
	end


	#get - render sps in json for typeahead
	def sp_list
		sps = SpRegistration.sps
		render json: sps
	end


	#put
	#FIXME sort this and edit out with teddy
	def update
		entityId = params[:entityId].strip
		@sp = SpRegistration.search(entityId)
		authorize_sp_user(@sp)
		render json: @sp
	end


	def attribute_approval
		# should be admin
		# 1. get total_option approve/disapprove
		# 2. get ids and delete or update or this should be 1

		#TODO pass in params and move into a model
		if params.has_key?(:total_option)
			ids = []

			ids = params[:approval_action]
			if params[:total_option] == 'approve'
				ids.each do |id|
					pending_attr = Spreg::PendingSpAttr.find(id)
					pending_attr.update({is_approved: 1}) if !pending_attr.nil?
				end
			elsif params[:total_option] == 'disapprove'
				ids.each do |id|
					pending_attr = Spreg::PendingSpAttr.find(id).destroy
				end
			end
		end
		redirect_back(fallback_location: root_path)
	end
end

app/helpers/spreg_helper.rb
module SpregHelper
  def format_display_certificate(cert)
    cert = cert.scan(/.{1,64}/)
    cert.map! do |c|
      c = "<p class='certline'>" + c + "</p>"
    end

    cert.join
  end
end

app/views/admin/spreg/_pending_attr_approvals.erb
<% if @pending_sp_attrs.empty? %>
  <h5>No pending attribute requests</h5>
<% else %>
  <%= form_tag(attribute_approval_path) do %>
    <table class="idms-data-table manage_pending_table display full-width">
      <tr>
        <th class="checkbox">Check All <br />
          <input type="checkbox" id="check_all" value="Check All" />
        </th>
        <th>Entity ID</th>
        <th>Attribute</th>
        <th>Value</th>
        <th>Reg Ex</th>
        <th>Reason</th>
      </tr>

      <% @pending_sp_attrs.each do |pending_attr| %>
        <% attribute = Spreg::Attribute.find(pending_attr.attribute_id) %>

        <tr>
          <td class="checkbox"><%= check_box_tag 'approval_action[]', pending_attr.id %></td>
          <td><%= pending_attr.sp.entity_id %></td>
          <td><%= attribute.attributeID %></td>
          <td><%= pending_attr.value %></td>
          <td><%= pending_attr.is_value_regex ? 'Yes' : 'No' %></td>
          <td><%= pending_attr.reason %></td>
        </tr>
      <% end %>
    </table>

    <fieldset class="radiogroup">
      <legend>Approve or Disapprove restricted attribute requests:</legend>
      <ul class="radio">
        <li><input type="radio" name="total_option" id="total_option_approve" value="approve" />&nbsp;Approve Request</li>
        <li><input type="radio" name="total_option" id="total_option_disapprove" value="disapprove" />&nbsp;Disapprove Request</li>
      </ul>
    </fieldset>

    <%= submit_tag "Submit", class: "create-btn" %>
  <% end %>
  </div>

  <script type="text/javascript">
    $('#check_all').change(function() {
      $('table.manage_pending_table input[type="checkbox"]').prop('checked', $(this).is(':checked'));
    });
  </script>
<% end %>

app/views/admin/spreg/_search.html.erb
<h2 id="spreg-header">SP Registration - Search by Entity ID</h2>
<div class="content-section">
  <%= form_tag(search_sp_path) do  %>

    <div id="prefetch">
      <%= search_field_tag 'entityId', nil ,placeholder: 'entityID', class: "typeahead typeahead-bar" %>
    </div>
    <%= submit_tag 'Search Entity ID', class: 'active' %>

  <% end %>
</div>
<h2>SP Registration - Search by NetID</h2>

<div class="content-section">
  <%= form_tag(search_by_user_path) do  %>
    <%= search_field_tag 'netid', nil ,placeholder: 'netid' %>
    <%= submit_tag 'Search NetID', class: 'active' %>
  <% end %>
</div>

app/views/admin/spreg/index.html.erb
<div id="main-no-aside">
  <% if flash[:error] %>
    <div class="message error">
      <%= flash[:error] %>
    </div>
  <% elsif flash[:notice] %>
    <div class="message notice">
      <%= flash[:notice] %>
    </div>
  <% end %>



  <%= render :partial => "search" %>

  <% if @potential_matches %>
    <%= form_tag(show_sp_path, method: "get", id: "sp-search-form") do  %>
    <table class="display full-width tablesorter">
      <thead>
        <tr>
          <th>Entity ID</th>
        </tr>
      </thead>
      <tbody>
        <% @potential_matches.each do |m| %>
          <tr class="click-row potential-sp-row">
            <td><%= m %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  <% end %>


  <h2>Pending Attribute Approvals</h2>
  <%= render :partial => "pending_attr_approvals" %>

</div>

app/views/admin/spreg/show.html.erb
  <% if flash[:success] %>
    <div class="message success">
      <%= flash[:success].html_safe %>
    </div>
  <% elsif flash[:error]%>
    <div class="message error">
      <%= flash[:error].html_safe %>
    </div>
  <% end %>

  <% if @pending %>
    <div class="message notice ">
      <p>This registration is currently awaiting updates in our system.</p>
      <p>You will be unable to alter this registration until updates are complete.</p>
      <p>Please allow 5-10 minutes for changes updates to complete.</p>
    </div>
  <% end %>

  <div class="message error" id="spreg-error-container">
  </div>


  <%= render :partial => 'admin/spreg/search' if @is_admin %>

  <% if @sp.sp %>
    <% details = @sp.spreg_details %>
    <%= form_tag(delete_sp_path(entityId: @sp.entity_id), method: :delete) do %>
      <h1 class='idms-h1'>
        <%= @sp.entity_id %>
        <button id="delete-sp-btn" class="idms-del" type="submit" onclick="return confirm('Are you sure you want to delete this registration?')">
          <i class='fa fa-trash' aria-hidden='true'></i>
        </button>
      </h1>

    <% end %>

    <%= form_tag(edit_sp_path , id: 'spreg-form') do %>

      <h3>Details</h3>
      <div class='form-set sp-info content-section'>
        <h4 class='sp-header'>Info</h4> <span class="sp-edit-icon sp-icon"><i class='fa fa-edit' aria-hidden='true'></i></span>
        <% entity_id = @sp.entity_id %>
        <% purpose = details[:purpose] %>
        <% responsible_department = details[:responsible_dept] %>
        <% owning_department = details[:owner_dept] %>
        <% audience = details[:audience] %>


        <%= label_tag :entity_id, 'Entity ID' %>
        <p class="sp-show-field"><%= entity_id %></p>
        <span class='bold-title sp-update-field'><%= text_field_tag :entity_id, entity_id, placeholder: entity_id%> </span>
        <%= hidden_field_tag :base_entity_id, entity_id %>

        <%= label_tag :purpose, "Purpose" %>
        <p class='sp-show-field'><%= purpose %></p>
        <span class='bold-title sp-update-field'><%= text_field_tag :purpose, purpose, placeholder: purpose%></span>

        <%= label_tag :responsible_department, 'Responsible Department' %>
        <p class='sp-show-field'><%= responsible_department %></p>
        <span class='bold-title sp-update-field'><%= text_field_tag :responsible_department, responsible_department, placeholder: responsible_department%> </span>

        <%= label_tag :owning_department, 'Owning Department' %>
        <p class='sp-show-field'> <%= owning_department %></p>
        <span class='bold-title sp-update-field'><%= text_field_tag :owning_department, owning_department, placeholder: owning_department%> </span>

        <%= label_tag :audience, "Audience" %>
        <p class='sp-show-field'><%= audience %></p>
        <span class='bold-title sp-update-field'><%= text_field_tag :audience, audience, placeholder: audience%></span>
      </div>



      <div class='sp-info content-section'>
        <h4 class='sp-header'>Users - People able to access and edit the registration.</h4> <span class="sp-icon sp-edit-icon"><i class='fa fa-edit' aria-hidden='true'></i></span>
        <% details[:users].each do |user|  %>
          <p class='sp-show-field'><span class='bold-title'><%= user %></p>
        <% end %>

        <div class='sp-update-field oneRequired'>
          <p class='dup-spreg-field'>+ Add User NetID</p>
          <% details[:users].each do |user|  %>
            <div class='sp-dup-set'>
              <%= text_field_tag 'users[]', user, placeholder: "netid", class: 'sp-users-netid'%>
              <span id="delete-sp-attr-example" class="delete-sp-field"><i class='fa fa-trash delete-sp-field' aria-hidden='true'></i></span>
            </div>
          <% end %>
        </div>
      </div>


      <div class="content-section">
        <h3 class='sp-header'>Certificate </h3><span class="sp-icon sp-edit-icon"><i class='fa fa-edit' aria-hidden='true'></i></span>
        <p>This is the certificate for response encryption. Do not confuse this with a web server certificate.</p>
        <div class='clearfix'></div>
        <div id="cert-container" class='sp-show-field'>
          <% cert =  @sp.certificate[:full_cert] %>
          <%# cert.scan(/.{1,64}/).join("\n") %>
          <code id='sp-cert' >

              <%# format_display_certificate(cert).html_safe %>
              <%= sanitize format_display_certificate(cert) %>


          </code>
        </div>
        <%= text_area_tag(:cert, cert, class: 'sp-update-field') %>

        <div class='cert-details'>
          <div class='sp-info'>
            <h4>Subject</h4>
            <% format_issuer_subject(@sp.certificate[:subject]).each do |s| %>
              <ul><%= s %></ul>
            <% end %>
          </div>
        </div>

        <div class='cert-details'>
          <div class='sp-info'>
            <h4>Issuer</h4>
            <% format_issuer_subject(@sp.certificate[:issuer]).each do |s| %>
              <ul><%= s %></ul>
            <% end %>
          </div>
        </div>

        <div class='sp-info'>
          <p><span class='bold-title'>Serial:</span> <%= @sp.certificate[:serial] %></p>
          <p><span class='bold-title'>Not Before:</span> <%= @sp.certificate[:before] %></p>
          <p><span class='bold-title'>Not After:</span> <%= @sp.certificate[:after] %></p>
        </div>
      </div>


      <div class="content-section">
        <h3 class='sp-header'>ACS </h3><span class="sp-icon sp-edit-icon"><i class='fa fa-edit' aria-hidden='true'></i></span>

        <div class='sp-show-field'>
          <% @sp.acs.each do |a| %>
            <div class='sp-info acs-info'>
              <p><span class='bold-title'>Location: </span><%= a[:location] %>  <%= a[:is_default] %></p>
              <p><span class='bold-title'>Binding: </span><%= a[:binding] %></p>
            </div>
          <% end %>
        </div>

        <div class='sp-update-field oneRequired'>
          <% acs_bindings = {'2.0:bindings:HTTP-POST' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST', '1.0:profiles:browser-post' => 'urn:oasis:names:tc:SAML:1.0:profiles:browser-post', '2.0:bindings:HTTP-POST-SimpleSign' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign'} %>
          <p class='dup-spreg-field'>+ Add ACS </p>
          <% @sp.acs.each do |a| %>
            <div class='sp-dup-set'>
              <span class='bold-title'>Default ACS:</span>
              <%= radio_button_tag 'acs[]is_default', nil, a[:is_default] %>
              <%= text_field_tag 'acs[]location', a[:location], placeholder: "location", class: "sp-long-field sp-acs"%>
              <%= select_tag 'acs[]binding', options_for_select(acs_bindings.collect{ |k,v| [k, v]}, a[:binding]) %>
              <span class="delete-sp-field"><i class='fa fa-trash delete-sp-field' aria-hidden='true'></i></span>
            </div>
          <% end %>
        </div>
      </div>

      <div class="content-section">
        <h3 class='sp-header'>Released Attributes</h3><span class="sp-icon sp-edit-icon"><i class='fa fa-edit' aria-hidden='true'></i></span>
        <div class='sp-show-field'>
          <p class='released-attribute'>eduPersonPrincipalName</p>
          <p class='released-attribute'>eduPersonScopedAffiliation</p>
          <% @sp.attributes.each do |attr| %>
            <p class='released-attribute'><%= attr[:name] %></p>
          <% end %>
        </div>

        <div class='sp-update-field sp-attr-update-fields'>
          <% attrs = attr_collection(@attributes) %>
          <%= select_tag :newAttr, options_for_select(attrs.collect{ |k,v| [k, v] }) , class: 'long-text-field', id: 'new-sp-attr'%> <span class="add-sp-attr-btn"><i class='fa fa-plus add-sp-attr-btn' aria-hidden='true'></i></span>
          <% @sp.attributes.each do |a| %>
            <div class='sp-dup-set'>
              <%= hidden_field_tag 'attributes[][is_public]', a[:is_public]  %>
              <%= text_field_tag 'attributes[][attr]', a[:name], readonly: 'readonly', class: 'long-text-field'%> <span class="delete-sp-field"><i class='fa fa-trash' aria-hidden='true'></i></span>
            </div>
          <% end %>
        </div>
      </div>


      <div class="content-section">
        <!--groups-->
        <h3 class='sp-header'>Released Groups</h3> <span class="sp-edit-icon sp-icon"><i class='fa fa-edit ' aria-hidden='true'></i></span>
        <% unless @sp.groups.empty? %>
          <div class='sp-show-field'>
            <% @sp.groups.each do |g| %>
              <p class='released-attribute'><%= g[:group] %></p>
            <% end %>
          </div>
        <% end %>


        <div class='sp-update-field sp-group-update-fields'>
          <p class='dup-spreg-field'> + Add Group </p>
          <% if @sp.groups.empty? %>
            <div class='sp-dup-set'>
              <span class='bold-title'>Regex Value?:</span>
              <%= hidden_field_tag 'groups[][is_value_regex]', "0" %>
              <%= check_box_tag 'groups[][is_value_regex]'%>
              <%= text_field_tag 'groups[][path]', nil,placeholder: 'type in group path here',class: 'sp-long-field sp-edit-group-field' %>
              <span class="delete-sp-field"><i class='fa fa-trash' aria-hidden='true'></i></span>
            </div>
          <% else %>
            <% @sp.groups.each do |g| %>
              <div class='sp-dup-set'>
                <span class='bold-title'>Regex Value?:</span>
                <%= hidden_field_tag 'groups[][is_value_regex]', "0" %>
                <%= check_box_tag 'groups[][is_value_regex]' , true ,g[:regex]%>
                <%= text_field_tag 'groups[][path]', g[:group], placeholder: 'type in group path here', class: 'sp-long-field sp-edit-group-field' %>
                <span class="delete-sp-field"><i class='fa fa-trash' aria-hidden='true'></i></span>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class='clearfix'></div>

      <% unless @pending %>
        <div id='update-sp-container'>
          <h3>Commit Your Changes!</h3>
          <p>Make updates to your registration and commit the changes to our Identity Provider.</p>
          <p>Please note the private attributes will require review/approval from the Identity Managment team.</p>
          <button class="active" id='spreg-submit'>Update SP</button>
        </div>
      <% end %>
    <% end %> <!-- end-form -->
  <% end %>